_target_: diffcsp.pl_modules.cspnet.CSPNet
hidden_dim: 512
latent_dim: 0
lattice_dim: 6
max_atoms: 100
num_layers: 6
act_fn: silu
dis_emb: sin
num_freqs: 128
rec_emb: none
num_millers: 5
edge_style: fc
max_neighbors: ${model.max_neighbors}
cutoff: ${model.radius}
ln: true
ip: false