- scheduler:
    _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
    _partial_: true
    factor: 0.6
    patience: 30
    min_lr: 1e-4
  interval: epoch
  frequency: 1
  monitor: train_loss
  strict: true