expname: test

# metadata specialised for each experiment
core:
  version: 0.0.1
  tags:
    - ${now:%Y-%m-%d}

hydra:
  run:
    dir: ${oc.env:HYDRA_JOBS}/singlerun/${expname}/

  sweep:
    dir: ${oc.env:HYDRA_JOBS}/multirun/${expname}/
    subdir: ${hydra.job.num}_${hydra.job.id}

  job:
    chdir: false
    env_set:
      WANDB_START_METHOD: thread

defaults:
  - data: default
  - logging: default
  - model: diffusion
  - optim: default
  - train: default
  - override hydra/job_logging: custom
  - _self_
#    Decomment this parameter to get parallel job running
  # - override hydra/launcher: joblib
