_target_: crystalflow.models.vfield.gnn.SimpleGNN
mode: ${..mode}
type_dim: ${..type_model.dim}
type_need_smooth: ${..type_model.need_smooth}
time_dim: 256
hidden_dim: 512
num_layers: 6
frac_emb_freq: 256
edge_style: fc
act_fn: silu
final_layer_norm: true