_target_: crystalflow.models.vfield.gnn.SimpleGNN
hidden_dim: 128
num_layers: 4
time_dim: 256
frac_emb_freq: 128
edge_style: fc
act_fn: silu
final_layer_norm: true
type_model:
  _target_: crystalflow.models.type_model.AtomTypeModule
  encode_mode: embeddingminus1
  out_dim: 128