_target_: diffcsp.pl_modules.flow.CSPFlow
time_dim: 256
latent_dim: 0
cost_type: 1.
cost_coord: 1.
cost_lattice: 1.
max_neighbors: 20  # maximum number of neighbors for OTF graph bulding in decoder
radius: 7.  # maximum search radius for OTF graph building in decoder
timesteps: 1000


defaults:
  - decoder: cspnet
  - beta_scheduler: cosine
  - sigma_scheduler: wrapped
  - conditions: default
  - _self_

decoder:
  pred_type: true
  smooth: ${model.decoder.pred_type}
  smooth: true