expname: test
logmode: offline

random_seed: 42
float32_matmul_precision: high

hydra:
  run:
    dir: ${oc.env:HYDRA_JOBS,hydra}/crystalflow/${expname}/
  job:
    chdir: false
    env_set:
      WANDB_START_METHOD: thread

defaults:
  - data: default
  - pl_model: default
  - trainer: default
  - override hydra/job_logging: custom
  - _self_