expname: test
logmode: offline

hydra:
  run:
    dir: ${oc.env:HYDRA_JOBS,hydra}/crystalflow/${expname}/
  job:
    chdir: false
    env_set:
      WANDB_START_METHOD: thread

defaults:
  - data: default
  - pl_model: default
  - pl_model/model: default
  - pl_model/model/vfield: simple_gnn
  - trainer: default
  - override hydra/job_logging: custom
  - _self_